spring:
  data:
    mongodb:
      uri: ${mongodb.uri}
  application:
    name: notification-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka